### ISSUE TITLE
NTFS and HDDtemp

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [jrgp/linfo#109]
It seems loading ntfs drives doesn't list specs just ? marks. I installed hddtemp and got a hdd parser error. Other than that awesome tool. Thank you

**Comment by jrgp** [comment]
Thanks for reaching out & I'm glad you like the tool :)

Can you clarify what OS you're using, and also provide a screenshot of what you're seeing? Also, are you using the latest git checkout of linfo or an older release?

**Comment by PROBLEMCHYLD** [comment]
Slackware 14.2 using the latest git version from here. Again thank you for a wonderful tool.

**Comment by PROBLEMCHYLD** [comment]
Highlighted in blue is my NTFS drive.

![Screenshot_2020-01-10_03-07-08](https://user-images.githubusercontent.com/30463992/72141224-0dce8b80-3358-11ea-8c31-734938b915a8.png)

**Comment by jrgp** [comment]
1) As for your question of hddtemp, it can't always detect temps from SSDs and some HDs.

2) As for those '?' in place of the disk usage stats, it's likely because the web server user does not have read permission on that `/run/media/problemchyld` path, so its statvfs calls fail.

If you make your web server php run as your username, or if you manually move the mountpoint somewhere else, or if you set /run and /run/media and /run/media/problemchyld to chmod 0755, then it might work.

**Comment by PROBLEMCHYLD** [comment]
Thanks, you can close this. Any future releases coming?

**Comment by jrgp** [comment]
Definitely. Feel free to suggest features you'd like to see in upcoming releases :)
